config/routes.rb
Blocipedia::Application.routes.draw do

  devise_for :users

  resources :wikis do 
    resources :articles 
  end

  root to: 'wikis#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title

  belongs_to :wiki
 
  validates :title, length: {minimum: 5},presence: true
  validates :body, length: {minimum: 10},presence: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    new_record?
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :role

  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable 

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :roles
  has_many :wikis, through: :roles

  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  attr_accessible :description, :subject

  has_many :articles
  has_many :users, through: :roles
  belongs_to :user
  

  default_scope order('created_at DESC')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @articles = @wiki.articles
  end

  def show
    @wiki = Wiki.find(params[:wiki_id])
    @article = Article.find(params[:id])
    if request.path != wiki_article_path(@wiki,@article)
      redirect_to [@wiki,@article], status: :moved_permanently
    end
  end

  def new
    @wiki = Wiki.find(params[:wiki_id])
    @article = Article.new
  end

  def edit
    @wiki = Wiki.find(params[:wiki_id])
    @article = Article.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:wiki_id])
     ## route to this article is wikis/wiki_id/articles/id
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      ##params is == to the hash article not just one column 
      flash[:notice] = "Article was updated."
      redirect_to [@wiki,@article]
    else
      flash[:error] = "There was an error saving the article. Please try again."
      render :edit 
    end
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @article = Article.new(params[:article])
    @article.wiki = @wiki
    if @article.save
      flash[:notice] = "Article was saved."
      redirect_to [@wiki,@article]
    else
      flash[:error] = " There was an error saving the article. Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @article = Article.find(params[:id])
    title = @article.title
    if @article.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @wiki ##redirect_to[@wiki,:articles] or wiki_articles_path(@wiki)
    else
      flash[:error] = "\"#{title}\" was deleted successfully."
                    ##/wikis/:wiki_id/articles 
      render :show
    end
  end 

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = Wiki.all
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def show
    @wiki = Wiki.find(params[:id])
    @wiki.articles 
    authorize @wiki   
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(params[:wiki])
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @wiki
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    if @wiki.update_attributes(params[:wiki])
      flash[:notice] = "Wiki was updated"
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again"
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    subject = @wiki.subject
    authorize @wiki
    if @wiki.destroy
      flash[:notice] = "\"#{subject}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end





end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/articles/_form.html.haml
.eight.columns
  = form_for [wiki,article] do |f|
    = f.text_field :title, class: "title"
    = f.text_area :body, rows: 20, class: "body"
    = f.submit "Save", class: 'btn'
.eight.columns
  .preview
    .title
    .body      

app/views/articles/edit.html.haml
.container


  %h1 Edit Article 

  = render partial: 'form', locals: { wiki: @wiki, article: @article }

app/views/articles/index.html.haml
.container


  %h1 Articles

  .row
    .columns.eight
    - @articles.each do |article|
      %h4= link_to (markdown article.title), article 
      %small= link_to "Edit", edit_article_path(article)
    
    .columns.four
      = link_to "New Article", new_article_path, class: 'button'

app/views/articles/new.html.haml
.container


  %h1 New Article
  = render partial: 'form', locals: { wiki: @wiki, article: @article }

app/views/articles/show.html.haml
.container

  .row
    .columns.eight
      %h1= markdown @article.title
      %p=  markdown @article.body
      = link_to "Edit", edit_wiki_article_path(@wiki,@article), class: 'button'
      = link_to "Delete Article", [@wiki,@article], method: :delete, class: 'button', confirm: 'Are you sure you want to delete this?'
    .columns.five
      = link_to "New Article", new_wiki_article_path(@wiki), class: 'button'
    

app/views/layouts/application.html.erb
<!DOCTYPE html>


<html>
<head>

  <title>Blocipedia</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <h2><strong>BLOCEPDI</strong></h2>
    <div class='row'>

        <nav>
        
          <li ><%= link_to "Blocepdia", root_path%></li>
          <li ><%= link_to "Wiki", wikis_path%></li>
        

        <div class= "offset-by-eight">
          <%if current_user %>
            Hello <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
          <%else%>
            <%= link_to "Sign In", new_user_session_path %> or 
            <%= link_to "Sign Up", new_user_registration_path %>
          <%end%>

        </div>        
      </nav>
    </div>

<%= yield %>


</div>
</body>
</html>

app/views/wikis/_form.html.haml
.eight.columns
  = form_for wiki do |f|
    = f.text_field :subject, class: "title"
    = f.text_area :description, rows: 20, class: "body"
    = f.submit "Save", class: 'btn'
.eight.columns
  .preview
    .title
    .body

app/views/wikis/edit.html.haml
.container


  %h1 Edit Wiki
  = render partial: 'form', locals: { wiki: @wiki}

app/views/wikis/index.html.haml
.container

  %h1 Wikis

  .row
    .columns.eight
      -@wikis.each do |wiki|
        %h4
          = link_to wiki.subject, wiki
          %small= link_to "Edit", edit_wiki_path(wiki)
      
    .columns.two
      -if policy(Wiki.new).create?
        = link_to "New Wiki", new_wiki_path, class: 'button'

app/views/wikis/new.html.haml
.container

  %h1 New Wiki
  = render partial: 'form', locals: { wiki: @wiki}

app/views/wikis/show.html.haml
.container
  %div{class:"eight columns"}
    %h1= @wiki.subject
    %p= markdown @wiki.description
    %small
      = link_to "New Article", new_wiki_article_path(@wiki), class: 'button' 
      = link_to "Edit", edit_wiki_path(@wiki), class: 'button' if policy(@wiki).update? 
    = link_to "Delete wiki", @wiki, method: :delete, class: 'button',confirm: 'Are you sure you want to delete this?' if policy(@wiki).destroy? 
    %br
    %ul
      - @wiki.articles.each do |article|
        %li= link_to (markdown(article.title)), wiki_article_path(@wiki,article)
        